<table id="konten" class="table" style="width:100%;">
    <thead>
        <tr>
            <th>Judul</th>
            <th>Tanggal</th>
            <th>Gambar</th>
            <th>Author</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
        <tr>
            <th>Judul</th>
            <th>Tanggal</th>
            <th>Gambar</th>
            <th>Author</th>
            <th>Action</th>
        </tr>
    </tfoot>
</table>